# Generated by Django 5.1.7 on 2025-08-27 04:05

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(help_text='Ej: personas.ver, personas.crear', max_length=60, unique=True)),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.TextField(blank=True)),
                ('modulo', models.CharField(choices=[('home', 'Inicio'), ('personas', 'Personas'), ('empleados', 'Empleados')], db_index=True, max_length=30)),
                ('accion', models.CharField(choices=[('ver', 'Ver/Consultar'), ('crear', 'Crear'), ('editar', 'Editar'), ('inactivar', 'Inactivar'), ('exportar', 'Exportar/Descargar'), ('imprimir', 'Imprimir'), ('aprobar', 'Aprobar/Autorizar')], db_index=True, max_length=20)),
                ('url_name', models.CharField(blank=True, help_text='Nombre de URL de Django (opcional)', max_length=120, null=True)),
                ('http_method', models.CharField(choices=[('ANY', 'Cualquiera'), ('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], default='ANY', max_length=7)),
                ('visible_nav', models.BooleanField(default=False, help_text='Mostrar en el menú si el usuario tiene este permiso')),
                ('icono', models.CharField(blank=True, default='bi-shield-lock', max_length=50)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('requires_mfa', models.BooleanField(default=False)),
                ('vigente_desde', models.DateField(blank=True, null=True)),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bodega_permiso',
                'ordering': ['modulo', 'accion', 'codigo'],
                'indexes': [models.Index(fields=['modulo', 'accion'], name='idx_perm_mod_acc'), models.Index(fields=['url_name'], name='idx_perm_urlname')],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(db_index=True, max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('activo', models.BooleanField(db_index=True, default=True, editable=False)),
            ],
            options={
                'db_table': 'bodega_persona',
                'ordering': ['apellido', 'nombre'],
                'indexes': [models.Index(fields=['apellido', 'nombre'], name='idx_persona_nombre')],
            },
        ),
    ]
