# Generated by Django 5.1.7 on 2025-05-28 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0002_movimiento_almacen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='almacen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodega.almacen'),
        ),
    ]
