# Generated by Django 5.1.7 on 2025-08-27 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0002_remove_permiso_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permiso',
            name='modulo',
            field=models.CharField(choices=[('home', 'Inicio'), ('personas', 'Personas'), ('empleados', 'Empleados'), ('permisos', 'Permisos')], db_index=True, max_length=30),
        ),
    ]
