# Generated by Django 5.1.7 on 2025-04-01 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0002_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='permisos',
            field=models.ManyToManyField(related_name='roles', to='bodega.permiso'),
        ),
    ]
