# Generated by Django 5.1.7 on 2025-08-27 05:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0003_alter_permiso_modulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permiso',
            name='codigo',
            field=models.CharField(help_text='modulo.accion (ej.: personas.ver)', max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[a-z]+(\\.[a-z_]+)$', 'Usa formato modulo.accion en minúsculas (ej.: personas.ver).')]),
        ),
    ]
