# Generated by Django 5.1.7 on 2025-08-27 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0004_alter_permiso_codigo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permiso',
            options={'ordering': ['modulo', 'nombre']},
        ),
        migrations.RemoveField(
            model_name='permiso',
            name='orden',
        ),
    ]
