# Generated by Django 5.1.7 on 2025-06-09 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0004_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='facturado',
            field=models.BooleanField(default=False),
        ),
    ]
