# Generated by Django 5.1.7 on 2025-04-08 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0004_rol_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='salario',
        ),
        migrations.AddField(
            model_name='permiso',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
