# Generated by Django 5.1.7 on 2025-08-27 05:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0005_alter_permiso_options_remove_permiso_orden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permiso',
            name='http_method',
        ),
        migrations.RemoveField(
            model_name='permiso',
            name='icono',
        ),
        migrations.RemoveField(
            model_name='permiso',
            name='requires_mfa',
        ),
        migrations.RemoveField(
            model_name='permiso',
            name='visible_nav',
        ),
        migrations.AlterField(
            model_name='permiso',
            name='accion',
            field=models.CharField(choices=[('ver', 'Ver/Consultar'), ('crear', 'Crear'), ('editar', 'Editar'), ('inactivar', 'Inactivar')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='permiso',
            name='codigo',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[a-z]+(\\.[a-z_]+)$', 'Usa formato modulo.accion en minúsculas (ej.: personas.ver).')]),
        ),
    ]
