# Generated by Django 5.1.7 on 2025-06-17 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0005_pedido_facturado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='almacen_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bodega.almacen'),
        ),
    ]
