# Generated by Django 5.1.7 on 2025-08-27 16:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0006_remove_permiso_http_method_remove_permiso_icono_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permiso',
            name='vigente_desde',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='permiso',
            name='vigente_hasta',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
