# Generated by Django 5.1.7 on 2025-06-19 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0007_rename_stock_producto_stock_minimo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriaproducto',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='anio_cosecha',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='contenido_por_caja',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='graduacion_alcoholica',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='pais_origen',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='region',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='tipo_uva',
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo_bebida',
            field=models.CharField(blank=True, choices=[('vino', 'Vino'), ('cerveza', 'Cerveza'), ('otro', 'Otro')], max_length=50),
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos', to='bodega.categoriaproducto')),
            ],
        ),
    ]
