# Generated by Django 5.1.7 on 2025-08-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0007_alter_permiso_vigente_desde_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permiso',
            name='vigente_hasta',
        ),
        migrations.AlterField(
            model_name='permiso',
            name='vigente_desde',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
