# Generated by Django 5.1.7 on 2025-06-19 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0008_remove_categoriaproducto_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='codigo_barra',
        ),
    ]
