# Generated by Django 5.1.7 on 2025-08-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0008_remove_permiso_vigente_hasta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('permisos', models.ManyToManyField(blank=True, related_name='roles', to='bodega.permiso')),
            ],
            options={
                'db_table': 'bodega_rol',
                'ordering': ['nombre'],
            },
        ),
    ]
