# Generated by Django 5.1.7 on 2025-08-27 19:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0009_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='cedula',
            field=models.CharField(db_index=True, max_length=7, unique=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'La cédula debe contener solo números (sin puntos, guiones ni espacios).')]),
        ),
    ]
