# Generated by Django 5.1.7 on 2025-04-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0009_ordencompra_proveedor_detalleordencompra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='ruc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
