# Generated by Django 5.1.7 on 2025-08-13 08:09

import django.core.validators
import django.db.models.functions.text
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0009_remove_producto_codigo_barra'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='empleado',
                    name='activo',
                ),
                migrations.RemoveField(
                    model_name='cliente',
                    name='activo',
                ),
            ],
            database_operations=[],
        ),
        
        migrations.AlterModelOptions(
            name='cliente',
            options={'managed': False, 'ordering': ['-activo', 'apellido', 'nombre']},
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={'managed': False, 'ordering': ['-activo', 'apellido', 'nombre']},
        ),
        migrations.AlterModelOptions(
            name='persona',
            options={'ordering': ['apellido', 'nombre']},
        ),
        migrations.AddField(
            model_name='persona',
            name='activo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='barrio',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='ciudad',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='departamento',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='documento_num',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='documento_tipo',
            field=models.CharField(choices=[('CI', 'Cédula'), ('RUC', 'RUC'), ('OTRO', 'Otro')], default='CI', max_length=10),
        ),
        migrations.AddField(
            model_name='persona',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='pais',
            field=models.CharField(default='Paraguay', max_length=120),
        ),
        migrations.AddField(
            model_name='persona',
            name='ruc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='margen_ganancia',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Margen %', max_digits=5),
        ),
        migrations.AlterField(
            model_name='persona',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\+?\\d{7,15}$', 'Use formato internacional sin espacios, ej: +595981123456')]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddIndex(
            model_name='persona',
            index=models.Index(fields=['apellido', 'nombre'], name='idx_persona_nombre'),
        ),
        migrations.AddIndex(
            model_name='persona',
            index=models.Index(fields=['ruc'], name='idx_persona_ruc'),
        ),
        migrations.AddIndex(
            model_name='persona',
            index=models.Index(fields=['documento_tipo', 'documento_num'], name='idx_persona_doc'),
        ),
        migrations.AddConstraint(
            model_name='persona',
            constraint=models.UniqueConstraint(condition=models.Q(('documento_num__isnull', False)), fields=('documento_tipo', 'documento_num'), name='uq_persona_documento'),
        ),
        migrations.AddConstraint(
            model_name='persona',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), condition=models.Q(('email__isnull', False)), name='uq_persona_email_lower'),
        ),
        migrations.AlterModelTable(
            name='persona',
            table='bodega_persona',
        ),
    ]
