# Generated by Django 5.1.7 on 2025-08-19 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0010_alter_cliente_options_alter_empleado_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cliente',
            table='bodega_cliente',
        ),
        migrations.AlterModelTable(
            name='empleado',
            table='bodega_empleado',
        ),
    ]
