# Generated by Django 5.1.7 on 2025-08-07 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0010_requisicion_detallerequisicion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallerequisicion',
            options={'verbose_name': 'Ítem de requisición', 'verbose_name_plural': 'Ítems de requisición'},
        ),
    ]
