# Generated by Django 5.1.7 on 2025-04-11 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0010_proveedor_ruc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
