# Generated by Django 5.1.7 on 2025-08-27 20:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0010_alter_persona_cedula'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='usuarios', to='bodega.rol'),
        ),
        migrations.AlterField(
            model_name='permiso',
            name='modulo',
            field=models.CharField(choices=[('home', 'Inicio'), ('personas', 'Personas'), ('empleados', 'Empleados'), ('permisos', 'Permisos'), ('roles', 'Roles')], db_index=True, max_length=30),
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('default_roles', models.ManyToManyField(blank=True, related_name='cargos', to='bodega.rol')),
            ],
            options={
                'db_table': 'bodega_cargo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bodega.persona')),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('grupo_sanguineo', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True)),
                ('telefono', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?\\d{7,15}$', 'Use formato internacional sin espacios, ej: +595981123456')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('direccion', models.CharField(max_length=255)),
                ('barrio', models.CharField(max_length=120)),
                ('ciudad', models.CharField(max_length=120)),
                ('departamento', models.CharField(max_length=120)),
                ('pais', models.CharField(default='Paraguay', max_length=120)),
                ('codigo_postal', models.CharField(blank=True, max_length=12, null=True)),
                ('fecha_contratacion', models.DateField()),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('motivo_baja', models.CharField(blank=True, max_length=255, null=True)),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados', to='bodega.cargo')),
            ],
            options={
                'db_table': 'bodega_empleado',
                'ordering': ['-activo', 'apellido', 'nombre'],
                'indexes': [models.Index(fields=['fecha_contratacion'], name='idx_empleado_fecha_ingreso'), models.Index(fields=['email'], name='idx_empleado_email')],
            },
            bases=('bodega.persona',),
        ),
    ]
