# Generated by Django 5.1.7 on 2025-08-20 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0011_alter_detallerequisicion_options'),
        ('bodega', '0011_sync_models_state'),
    ]

    operations = [
    ]
