# Generated by Django 5.1.7 on 2025-04-11 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0011_alter_producto_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bodega.persona')),
                ('activo', models.BooleanField(default=True)),
            ],
            bases=('bodega.persona',),
        ),
    ]
