# Generated by Django 5.1.7 on 2025-08-27 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0011_usuario_roles_alter_permiso_modulo_cargo_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='tipo_persona',
            field=models.CharField(choices=[('F', 'Persona Física'), ('J', 'Persona Jurídica')], db_index=True, default='', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='persona',
            name='cedula',
            field=models.CharField(db_index=True, unique=True),
        ),
    ]
