# Generated by Django 5.1.7 on 2025-08-27 23:18

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0012_persona_tipo_persona_alter_persona_cedula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='codigo_postal',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='cedula',
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_alta',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='persona',
            name='numero_de_documento',
            field=models.CharField(blank=True, db_index=True, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]+$', 'El número de documento debe ser alfanumérico (sin espacios ni símbolos).')]),
        ),
        migrations.AddField(
            model_name='persona',
            name='ruc_base',
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='ruc_dv',
            field=models.CharField(blank=True, db_index=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='cargo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='empleados_cargo', to='bodega.rol'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_nacimiento',
            field=models.DateField(null=True, blank=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empleado',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empleado',
            name='grupo_sanguineo',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='persona',
            constraint=models.UniqueConstraint(fields=('ruc_base', 'ruc_dv'), name='uniq_persona_ruc'),
        ),
    ]
