# Generated by Django 5.1.7 on 2025-08-28 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0013_remove_empleado_codigo_postal_remove_persona_cedula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.date(1900, 1, 1)),
            preserve_default=False,
        ),
    ]
