# Generated by Django 5.1.7 on 2025-08-28 18:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0014_alter_empleado_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='numero_de_documento',
            field=models.CharField(db_index=True, default=111, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]+$', 'El número de documento debe ser alfanumérico (sin espacios ni símbolos).')]),
            preserve_default=False,
        ),
    ]
