# Generated by Django 5.1.7 on 2025-08-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0015_alter_persona_numero_de_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='ruc_base',
            field=models.CharField(db_index=True, default=111, max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='persona',
            name='ruc_dv',
            field=models.CharField(db_index=True, default=1, max_length=1),
            preserve_default=False,
        ),
    ]
