# Generated by Django 5.1.7 on 2025-08-28 19:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0016_alter_persona_ruc_base_alter_persona_ruc_dv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='numero_de_documento',
            field=models.CharField(blank=True, db_index=True, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]+$', 'El número de documento debe ser alfanumérico (sin espacios ni símbolos).')]),
        ),
        migrations.AlterField(
            model_name='persona',
            name='ruc_base',
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='ruc_dv',
            field=models.CharField(blank=True, db_index=True, max_length=1, null=True),
        ),
    ]
