# Generated by Django 5.1.7 on 2025-04-11 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0016_factura_detallefactura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallefactura',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
