# Generated by Django 5.1.7 on 2025-08-28 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0017_alter_persona_numero_de_documento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('CI', 'Cédula de identidad'), ('PAS', 'Pasaporte'), ('RUC', 'RUC'), ('OTRO', 'Otro documento')], db_index=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='apellido',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
